### PR TITLE
Allow fixture key to be an object and not just a string

### PR DESCRIPTION
**Pull request by janelletavares**
## Description of change

Collection will be empty for Notion and Spire source resources, as the interface is written for now.  We don't know the resource type related to a collection, so we have to allow empty collections.

Fixes https://github.com/meroxa/turbine-core/issues/153

## Type of change

- [ ]  New feature
- [x]  Bug fix
- [ ]  Refactor
- [ ]  Documentation

## How was this tested?

- [ ]  Unit Tests
- [ ]  Tested in staging
- [x]  Tested in minikube

## Demo

| before | after |
|--------|-------|
|
```shell
$ m app run
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "invalid ProcessCollectionRequest.Collection: embedded message failed validation | caused by: invalid Collection.Name: value length must be at least 1 runes"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"invalid ProcessCollectionRequest.Collection: embedded message failed validation | caused by: invalid Collection.Name: value length must be at least 1 runes", grpc_status:2, created_time:"2023-05-11T13:29:22.799764807-07:00"}"
>
```
|
```shell
$ m app run
Destination s3/notion-pages-with-character-count
----------------------
           index|record
            ----|----
               0|{"payload":{"after":{"metadata":{"notion.archived":"false","notion.createdBy":"{\"object\":\"user\",\"id\":\"ee6bdc50-6db2-4805-87d0-3ca2501f7773\"}","notion.createdTime":"2022-12-23T20:32:00Z","notion.lastEditedBy":"{\"object\":\"user\",\"id\":\"ee6bdc50-6db2-4805-87d0-3ca2501f7773\"}","notion.lastEditedTime":"2022-12-23T23:55:00Z","notion.parent":"{\"type\":\"workspace\",\"workspace\":true}","notion.title":"Blog Post","notion.url":"https://www.notion.so/Blog-Post-3812a92e742340e09f75d7c6669091d7"},"plaintext":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A iaculis at erat pellentesque adipiscing commodo. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Aliquet enim tortor at auctor urna nunc id cursus metus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus."},"before":null,"op":"c","source":{"conduit.source.connector.id":"a032099c-031e-44c6-98bb-9ff46f88744a","opencdc.readAt":"1675734727936759010","opencdc.version":"v1"},"transaction":null,"ts_ms":1675734727936},"schema":{"fields":[{"field":"before","fields":[{"field":"plaintext","type":"string"},{"field":"metadata","fields":[{"field":"notion.createdTime","type":"string"},{"field":"notion.lastEditedBy","type":"string"},{"field":"notion.lastEditedTime","type":"string"},{"field":"notion.parent","type":"string"},{"field":"notion.title","type":"string"},{"field":"notion.url","type":"string"},{"field":"notion.archived","type":"string"},{"field":"notion.createdBy","type":"string"}],"optional":true,"type":"struct"}],"optional":true,"type":"struct"},{"field":"after","fields":[{"field":"plaintext","type":"string"},{"field":"metadata","fields":[{"field":"notion.createdBy","type":"string"},{"field":"notion.createdTime","type":"string"},{"field":"notion.lastEditedBy","type":"string"},{"field":"notion.lastEditedTime","type":"string"},{"field":"notion.parent","type":"string"},{"field":"notion.title","type":"string"},{"field":"notion.url","type":"string"},{"field":"notion.archived","type":"string"}],"optional":true,"type":"struct"}],"optional":true,"type":"struct"},{"field":"source","fields":[{"field":"conduit.source.connector.id","type":"string"},{"field":"opencdc.version","type":"string"},{"field":"opencdc.readAt","type":"string"}],"optional":true,"type":"struct"},{"field":"op","type":"string"},{"field":"ts_ms","optional":true,"type":"int64"},{"field":"transaction","fields":[{"field":"id","type":"string"},{"field":"total_order","type":"int64"},{"field":"data_collection_order","type":"int64"}],"optional":true,"type":"struct"}],"name":"resource_2_482576.Envelope","type":"struct"}}
            ----|----
 records written|1

```
|

### CODE REVIEW

**Comment by lyuboxa** [comment]
Rather than relaxing the validation, can we use a default collection for these collection-less connectors? majority of connectors do have collections.

**Comment by janelletavares** [comment]
> Rather than relaxing the validation, can we use a default collection for these collection-less connectors? majority of connectors do have collections.

@lyuboxa our docs now say that it can be empty.  also turbine-js does not have these validations.  so one way or another, we should have a consistent experience that is well documented.  i'm open to whatever the collective agreement is. i think @justmisosoup and @ahmeroxa had some thoughts about how to make the interface clearer around empty collections.  maybe now is the time.

**Comment by lyuboxa** [comment]
@janelletavares i don't think any of the frameworks have that validation, so this is enforced strictly in turbine-core. 

it will be hard to do per collection validation in turbine and this will need to be pushed in the DAG at deployment

**Comment by janelletavares** [comment]
> @janelletavares i don't think any of the frameworks have that validation, so this is enforced strictly in turbine-core.
> 
> it will be hard to do per collection validation in turbine and this will need to be pushed in the DAG at deployment

@lyuboxa it was in the open turbine-py PR to move to core, but not merged as such. prior to core, we didn't explicitly require collections to be non-empty, but there were some unfortunate side effects in the "run" command for empty collections.  if we had a special collection like IGNORE or something, our example fixtures would also have to be updated.  this is all fine, we just have to decide.

**Review by ericcheatham — APPROVED** [review]

**Pull request merged**
